defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: digger
  password:

development:
  <<: *defaults
  database: db/digger_development.sqlite3

test:
  <<: *defaults
  database: db/digger_test.sqlite3